rfsimulator :
{
  serveraddr = "127.0.0.1";
  serverport = "4043";
  options = ("chanmod");
  modelname = "AWGN";
  IQfile = "/tmp/rfsimulator.iqs";
};

channelmod = {
  max_chan   = 10;
  modellist = "modellist_awgn";
  modellist_awgn = (
    {
      model_name      = "rfsimu_channel_enB0";
      type            = "AWGN";
      ploss_dB        = 0;
      noise_power_dB  = -16;
      forgetfact      = 0;
      offset          = 0;
      ds_tdl          = 0;
    },
    {
      model_name      = "rfsimu_channel_ue0";
      type            = "AWGN";
      ploss_dB        = 0;
      noise_power_dB  = -20;
      forgetfact      = 0;
      offset          = 0;
      ds_tdl          = 0;
    }
  );
};

log_config :
{
  global_log_level = "info";
  hw_log_level     = "info";
  phy_log_level    = "info";
  mac_log_level    = "info";
  rlc_log_level    = "info";
  pdcp_log_level   = "info";
  rrc_log_level    = "info";
};
