rfsimulator :
{
  serveraddr = "127.0.0.1";
  serverport = "4043";
  options = ("chanmod");
  modelname = "AWGN";
  IQfile = "/tmp/rfsimulator.iqs";
};

channelmod = {
  max_chan   = 10;
  modellist = "modellist_bictr";
  modellist_bictr = (
    {
      model_name                  = "rfsimu_channel_enB0";
      type                        = "BICTR_LUNAR";
      ploss_dB                    = 0;
      noise_power_dB              = -10;
      forgetfact                  = 0;
      offset                      = 0;
      ds_tdl                      = 0;
      bictr_tx_rx_dist            = 500.0;
      bictr_tx_height             = 10.0;
      bictr_rx_height             = 2.0;
      bictr_ref_count             = 5;
      bictr_ring_radius_min       = 5.0;
      bictr_ring_radius_max       = 300.0;
      bictr_ring_radius_uncert    = 15.0;
      bictr_ring_count            = 10;
      bictr_ref_attempt_per_ring  = 3;
      bictr_permit_real           = 6.847824;
      bictr_permit_real_std       = 0.007099;
      bictr_permit_imag           = 0.836473;
      bictr_permit_imag_std       = 0.001295;
      bictr_horiz_pol             = 0;
      bictr_fading_paths          = 0;
      bictr_doppler_spread        = 1.0;
    },
    {
      model_name                  = "rfsimu_channel_ue0";
      type                        = "BICTR_LUNAR";
      ploss_dB                    = 0;
      noise_power_dB              = -10;
      forgetfact                  = 0;
      offset                      = 0;
      ds_tdl                      = 0;
      bictr_tx_rx_dist            = 500.0;
      bictr_tx_height             = 2.0;
      bictr_rx_height             = 10.0;
      bictr_ref_count             = 5;
      bictr_ring_radius_min       = 5.0;
      bictr_ring_radius_max       = 300.0;
      bictr_ring_radius_uncert    = 15.0;
      bictr_ring_count            = 10;
      bictr_ref_attempt_per_ring  = 3;
      bictr_permit_real           = 6.847824;
      bictr_permit_real_std       = 0.007099;
      bictr_permit_imag           = 0.836473;
      bictr_permit_imag_std       = 0.001295;
      bictr_horiz_pol             = 0;
      bictr_fading_paths          = 0;
      bictr_doppler_spread        = 1.0;
    }
  );
};

log_config :
{
  global_log_level = "info";
  hw_log_level     = "info";
  phy_log_level    = "info";
  mac_log_level    = "info";
  rlc_log_level    = "info";
  pdcp_log_level   = "info";
  rrc_log_level    = "info";
};
